/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <math.h>

// Función suma a + b
int *
suma_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;
	result = a + b;
	return &result;
}

// Función resta a - b
int *
resta_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;
	result = a - b;
	return &result;
}

// Función multiplicación a x b
int *
multi_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;
	result = a * b;
	return &result;
}

// Función división a / b
div_res *
div_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static div_res  result;
	// Evitar dividir entre 0
	if (b == 0){
		return NULL;
		exit(0);
	} 
	else result.div_res_u.res = (int) a / b;
	return &result;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//         CALCULADORA COMPLEJA
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Función suma de vectores (archivo)
char **
suma_v_1_svc(char *fichero,  struct svc_req *rqstp)
{
	static char result[500] = { };
	static char * result_p;
	static char * error;

	// Abrimos el fichero
	FILE *file;
	if (!(file = fopen (fichero, "r"))) {
		error = "Error al abrir el fichero\n";
		return &error;
		exit(1);
	}

	// Leemos la longitud
	int longitud = 0;
	fscanf(file, "%d\n", &longitud);
	if (longitud == 0){
		fclose(file);
		error = "La longitud no puede ser 0\n";
		return &error;	
	}

	// Reservamos suficiente espacio para ambos vectores
	float vector1[longitud];
	float vector2[longitud];
	// Leemos el primer vector
	for (int i = 0; i < longitud; i++){
		if (fscanf(file,"%f",&vector1[i]) == EOF) {
			error = "Error: primer vector no válido\n";
			return &error;
		}
	}
	// Leemos el segundo vector
	for (int i = 0; i < longitud; i++){
		if (fscanf(file,"%f",&vector2[i]) == 0) {
			error = "Error: segundo vector no válido\n";
			return &error;
		}
	}

	// Fin lectura, cerramos el archivo
	fclose(file);
	
	// Realizamos la suma e imprimimos el vector
	char aux[100] = { };
	sprintf(result, "      ");
	for (int i = 0; i < longitud; i++){
		sprintf(aux,"%.2f ", vector1[i]);
		//aux_p = &aux[0];
		strcat(result, aux);
	}
	strcat(result, "\n +    ");
	for (int i = 0; i < longitud; i++){
		sprintf(aux,"%.2f ", vector2[i]);
		strcat(result, aux);
	}
	strcat(result, "\n   ");
	for (int i = 0; i < longitud; i++) strcat(result, "-----");
	strcat(result, "\n   ");
	for (int i = 0; i < longitud; i++){
		sprintf(aux,"%.2f ", vector1[i] + vector2[i]);
		strcat(result, aux);
	}
	result_p = result;
	
	return &result_p;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Funciones auxiliares determinante
float determinante(float * matrix, int longitud);

float cofactor(float * matrix, int longitud, int fila, int columna){
   float submatriz[longitud * longitud];
   int n = longitud - 1;
   int x = 0, y = 0;
   for (int i = 0; i < longitud; i++) {
      for (int j = 0; j < longitud; j++) {
         if (i != fila && j != columna) {
            submatriz[longitud*x + y] = *(matrix + j + longitud*i);
            y++;
            if (y >= n) {
               x++;
               y = 0;
            }
         }
      }
   }
   return pow(-1.0, fila + columna) * determinante(submatriz, n);
}

float determinante(float * matrix, int longitud) {
	float det = 0.0;
	if (longitud == 1) {
		det = *(matrix);

	} else {
    	for (int j = 0; j < longitud; j++) {
    		det = det + *(matrix + j) * cofactor(matrix, longitud, 0, j);
		}	
	}
	return det;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Función determinante de matriz (archivo)
char **
determ_1_svc(char *fichero, struct svc_req *rqstp)
{
	static char result[1000] = { };
	static char * result_p;
	static char * error;
	float * matrix_p;
	FILE *f;

	// Abrimos el fichero
	FILE *file;
	if (!(file = fopen (fichero, "r"))) {
		error = "Error al abrir el fichero\n";
		return &error;
		exit(1);
	}

	// Leemos la longitud
	int longitud = 0;
	fscanf(file, "%d\n", &longitud);
	if (longitud == 0){
		fclose(file);
		error = "La longitud no puede ser 0\n";
		return &error;	
	}

	// Reservamos suficiente espacio para la matriz y la leemos
	float matrix[longitud*longitud];
	for (int i = 0; i < longitud; i++){
		for (int j = 0; j < longitud; j++){
			if (fscanf(file,"%f",&matrix[j + longitud * i]) == EOF) {
				error = "Error: esta matriz no es válida\n";
				return &error;
			}
		}
	}

	// Fin de lectura, cerramos fichero
	fclose(file);

	char aux[100] = { };
	sprintf(result, "\n");
	// Imprimimos la matriz
	for (int i = 0; i < longitud; i++){
		strcat(result, "| ");
		for (int j = 0; j < longitud; j++) {
			sprintf(aux,"%.2f ", matrix[j+i*longitud]);
			strcat(result, aux);
		}
		if (i != longitud-1) strcat(result, "|\n");
		else strcat(result, "| = ");
	}
	
	// Cálculo del determinante
	sprintf(aux,"%.2f ", determinante (matrix, longitud));
	strcat(result, aux);
	
	result_p = result;
	return &result_p;
}

/* gcc calculadora_server.c calculadora_svc.c calculadora_xdr.c -o server -lnsl -lm */