/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>

// Función calculadora
int
calculadora_1(char *host, int first_number, char operator, int second_number)
{
	CLIENT *clnt;
	int * result;
	float * result_f;
	div_res  *result_div;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_V, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operator){
		case '+' : result = suma_1(first_number, second_number, clnt); break;
		case '-' : result = resta_1(first_number, second_number, clnt); break;
		case 'x' :
		case '*' : result = multi_1(first_number, second_number, clnt); break;
		case '/' : result_div = div_1(first_number, second_number, clnt);
					// Si se divide entre 0, lanzar error
					if (result_div == (div_res *) NULL) {
						clnt_perror(clnt, "Error: división entre 0\n");
						exit(1);
					} else return result_div->div_res_u.res; break;
		default : printf("Todavía no se ha implementado esa operación\n"); exit(0);
	}



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return * result;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Función calculadora compleja
char *
calculadora_compleja_1(char *host, int code, char * fichero)
{
	CLIENT *clnt;
	char  **result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_COMPLEJA, CALCULADORA_CV, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(code){
		// Llama a calculadora compleja 
		case 0: result = determ_1(fichero, clnt); break;
		case 1: result = suma_v_1(fichero, clnt); break;
		default: break;
	}
	printf("%s\n\n", *result);

	if (result == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return *result;
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                                 MAIN
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

int
main (int argc, char *argv[])
{
	char *host;
	int first_number, second_number, result;
	char operator;
	char fichero;

	if (argc < 5) {
		// Se podrá indicar la operación desde el menú, por lo que no salimos
		printf ("Para realizar una operación básica desde línea de comando use: \n");
		printf ("%s server_host first_number operator second_number\n\n", argv[0]);
	} else {
		// Se llama directamente a la calculadora
		host = argv[1];
		first_number = atoi(argv[2]);
		second_number = atoi(argv[4]);
		operator = *argv[3];
		result = calculadora_1 (host, first_number, operator, second_number);
		printf ("%d %s %d = %d\n\n", first_number, argv[3], second_number, result);
	}

	if (argc < 2) {
		// Este es el único parámetro obligatorio
		printf("Debe indicar el host\n");
		exit(1);
	}

	// Asignamos el host
	host = argv[1];

	while (1) {
		int opcion;
		// Menu: operaciones de calculadora básica y compleja
		printf ("¿Qué desea hacer?\n~~~~~~~~~~~~~~~~~~~~~~~\n");
		printf ("1. Sumar\n2. Restar\n3. Multiplicar\n4. Dividir\n5. Sumar dos vectores\n");
		printf ("6. Calcular el determinante de una matriz\n7. Salir\n\n");
		scanf("%d", &opcion);
		if (opcion < 5) {
			// Calculadora básica
			// Lectura de parámetros
			printf ("\n\nIntroduzca el primer número: ");
			scanf ("%d", &first_number);
			printf("Introduzca el segundo número: ");
			scanf ("%d", &second_number);
			// Llamada a calculadora
			switch (opcion){
				case 1: operator = '+'; break;
				case 2: operator = '-'; break;
				case 3: operator = '*'; break;
				case 4: operator = '/'; break;
				default: break;
			}
			result = calculadora_1 (host, first_number, operator, second_number);
			// Imprimimos el resultado
			printf ("%d %c %d = %d\n\n", first_number, operator, second_number, result);
		} else if (opcion < 7) {
			// Calculadora compleja
			//char * fichero;
			char * cadena;
			// Leeremos un fichero
			switch (opcion) {
				case 5: printf ("Introduzca el fichero donde se encuentran los vectores: "); break;
				case 6: printf ("Introduzca el fichero donde se encuentra la matriz regular: "); break;
				default: break;
			}
			scanf("%s", &fichero);
			cadena = calculadora_compleja_1(host, (opcion + 1)%2, &fichero);
			//printf("%s", cadena);
		} else exit(0);
	}
}

/* gcc calculadora_client.c calculadora_clnt.c calculadora_xdr.c -o client -lnsl */